### ISSUE TITLE
java.sql.SQLException: No suitable driver

### ISSUE THREAD

**Issue by saikiranbandaru** [Azure/azure-sqldb-spark#17]
Hello,

I am unable to execute my code as Spark fails due to lack of a suitable driver. Is there any particular configuration I need to set in my Config()? I'm using SQL Server.

Am I supposed to set the driver class manually? And is there any particular format for the URL?

Thanks

**Comment by Jasper-M** [comment]
Yes, you have to add `"driver" -> "com.microsoft.sqlserver.jdbc.SQLServerDriver"` to the `Config`.
I think the library should do this automatically. Since it makes no mention of having to set it manually and it's already [partly hardcoded](https://github.com/Azure/azure-sqldb-spark/blob/1.0.2/src/main/scala/com/microsoft/azure/sqldb/spark/config/SqlDBConfig.scala#L110).

**Comment by Fokko** [comment]
@saikiranbandaru Did this solve it for you?

**Comment by arvindshmicrosoft** [comment]
Thank you @Jasper-M for your suggestion; I hoped it helped the OP. Closing this due to lack of response.
