### ISSUE TITLE
Intermediate Commit support - Bulk Insert mode

### ISSUE THREAD

**Issue by bthebasics** [Azure/azure-sqldb-spark#23]
We are big consumer of Spark SQL connector as we are using this connector to read from various big data sources and dump into SQL Server 2016 datamart, One of the big issue faced was while using bulk-insert utility, we want to commit after each batch , so that transaction log is not filled up;
Can above be achieved? is there existing support or settings which can be leveraged for this requirement? please suggest.

Details :

We are using SQL Server 2016- on premise version + Spark 2.3
Referring to main article link : https://docs.microsoft.com/en-us/azure/sql-database/sql-database-spark-connector
Required --> Intermediate commit support after each batch to avoid filling of the transaction log - while Writing data to SQL Server using "Bulk Insert", default behavior is commit after complete data or all batches are written.

**Comment by arvindshmicrosoft** [comment]
Each Spark task uses a top-level transaction to ensure that task failures / retries do not result in duplicated data. Assuming your dataframe is partitioned appropriately, this connector will implicitly "batch" at that partition level. Do check your dataframe is partitioned - you can check this implicitly by observing the number of tasks which spin up when you call the bulkCopyToSqlDB method (you should see more than 1 task). If you have just 1 task call .repartition() on the dataframe prior to doing the bulk insert.

**Comment by ankitbko** [comment]
@arvindshmicrosoft having multiple partitions leads to deadlock and get below error. Only 1 partition executes and other tasks fails with below error - 
```
com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 153) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
```

**Comment by arvindshmicrosoft** [comment]
Sorry, @ankitbko, I am not sure how the deadlock you encountered is related to the OP's question. In any case, the deadlock would typically be due to [conflicting index key order](https://social.msdn.microsoft.com/forums/sqlserver/en-US/932cd26c-53fc-49c0-b082-e7f5f05a9801/deadlock-when-using-sqlbulkcopy-to-concurrently-insert-rows-into-a-single-nonempty-table), and / or [constraint checking](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms186247(v=sql.105)?redirectedfrom=MSDN).

Closing this as the question is not specific to the connector, and is instead the more general case of having multiple concurrent bulk inserts into the same table, and deadlocking.
