### ISSUE TITLE
value sqlDb is not a member of org.apache.spark.sql.DataFrameReader

### ISSUE THREAD

**Issue by thu-pham** [Azure/azure-sqldb-spark#52]
When I tried to run the below code, I got the error: `value sqlDb is not a member of org.apache.spark.sql.DataFrameReader`.

```// Use Spark Connector
import com.microsoft.azure.sqldb.spark.config.Config`
import com.microsoft.azure.sqldb.spark.connect._`
val config = Config(Map(
  "url"          -> "***",
  "databaseName" -> "***",
  "queryCustom"  -> "SELECT * FROM dbo.Table_1", //Sql query
  "user"         -> "***",
  "password"     -> "***"
))

//Read all data in table dbo.Table_1
val collection = sqlContext.read.sqlDb(config)
collection.show()
```

In fact, when I typed `sqlContext.read.` and hit tab to show the available options, there's none for "sqlDB" or "sqlDb". I'm using **azure-sqldb-spark-1.0.2-jar-with-dependencies.jar** from this release: https://github.com/Azure/azure-sqldb-spark/releases/tag/1.0.2

**Comment by vlado101** [comment]
I am facing the same issue as well. I copied the syntax directly from Microsoft website.

**Comment by arvindshmicrosoft** [comment]
The most likely reasons are due to the library JAR not being in classpath. In Azure Databricks, usually a detach-attach notebook cycle (post uploading and installing the library JAR) is all that is needed. Please follow up with more details (environment, version of Spark, error message if you try to run this simple example etc.) if you need anything further on this, else this issue will be closed by Aug 28, 2020.

**Comment by arvindshmicrosoft** [comment]
Closing due to age and inactivity.
