### ISSUE TITLE
databricks could not download dependencies from Maven repository

### ISSUE THREAD

**Issue by sunscorch** [Azure/azure-sqldb-spark#88]
try to install this lib from databricks. We encounter this error.  this a transient issue and want to know why this will occur

` Library installation failed for library maven { coordinates: 'com.microsoft.azure:azure-sqldb-spark:1.0.2' } . Error messages: Library resolution failed. Cause: java.lang.RuntimeException: Cannot download some libraries due to transient Maven issue. Please try again later. at com.databricks.libraries.server.MavenInstaller.downloadMavenPackagesWithRetry(MavenLibraryResolver.scala:166) at com.databricks.libraries.server.MavenInstaller.resolveMavenPackages(MavenLibraryResolver.scala:113) at com.databricks.libraries.server.MavenLibraryResolver.resolve(MavenLibraryResolver.scala:44) at com.databricks.libraries.server.ManagedLibraryManager$GenericManagedLibraryResolver.resolve(ManagedLibraryManager.scala:241) at com.databricks.libraries.server.ManagedLibraryManagerImpl.$anonfun$resolvePrimitives$1(ManagedLibraryManagerImpl.scala:193) at com.databricks.libraries.server.ManagedLibraryMan ... ***WARNING: message truncated. Skipped 1712 bytes of output**`

**Comment by arvindshmicrosoft** [comment]
If the issues connecting to Maven from Databricks are persistent, the best option would be to download the JAR manually, and then upload it using the Library functionality in Databricks as suggested [here](https://stackoverflow.com/questions/61574927/databricks-error-while-adding-maven-dependency-cannot-download-some-libraries).

As this library is not actively maintained and the above issue is most likely due to environment-specific reasons, I am closing this issue. Thank you for your understanding.
